### ISSUE TITLE
ESP unable to update because .bin file is missing on blob storage

### ISSUE THREAD

**Issue by thegreatdane6** [MaibornWolff/clean-air#56]

**Comment by thegreatdane6** [comment]
I manually added a new Firmware in the blobstorage. OTA is working as expected.

**Comment by angrox** [comment]
Please have a look at #64. This will create a firmware file and a LATEST file under https://github.com/MaibornWolff/clean-air/releases/latest/download/, as soon as the first release is created. The URL will always give you an redirect to the latest release so the http call inside the ESP must handle the redirect.

**Comment by thegreatdane6** [comment]
fixed by #71
