### ISSUE TITLE
Devices max. flash size exceeded

### ISSUE THREAD

**Issue by thegreatdane6** [MaibornWolff/clean-air#74]
We need to reduce the flash size or adjust the partitions because currently we are using 105% of the flashs size

**Comment by angrox** [comment]
This is probably a problem of the board configuration in platformio. Currently we are using a ESP32-WROOM-32 Unit bought from AZ-Delivery. This device seems to have 4MB eeprom and 520 kb ram. The platformio configuration has a board configured which shows 4mb eeprom and 320 kb ram.

Documentation links: 
* https://www.espressif.com/sites/default/files/documentation/esp32-wroom-32_datasheet_en.pdf
* https://www.az-delivery.de/en/products/esp32-d1-mini#description
