### ISSUE TITLE
Import of STLs into Slicer -> too small

### ISSUE THREAD

**Issue by thorsten** [MaibornWolff/clean-air#81]
**Describe the bug**
I cloned the repo and imported the STLs in PrusaSclicer. They look very small, only 21x21mm for the Lichtschutz.

**Screenshots**
<img width="2300" alt="Bildschirmfoto 2021-02-18 um 08 23 36" src="https://user-images.githubusercontent.com/45284/108320306-ec7ad880-71c2-11eb-96ee-aceab6c947ce.png">

**Hardware (please add the relevant information):**
 - Prusa MK3S+

**Software (please add the relevant information):**
 - PrusaSlicer 2.3

**Comment by thegreatdane6** [comment]
I will fix this, this is due to some export error. A workaround for this is to skale the part up to 1000% :)

**Comment by thorsten** [comment]
210x210mm is too large?

<img width="2560" alt="Bildschirmfoto 2021-02-18 um 08 31 24" src="https://user-images.githubusercontent.com/45284/108320926-bb4ed800-71c3-11eb-818a-3c68c15e72db.png">

**Comment by felixherbst** [comment]
210*210 fits on a prusa, if you remove the skirt ("Schürze"). Just set the amount to 0.
![image](https://user-images.githubusercontent.com/8899664/108321942-1e8d3a00-71c5-11eb-904c-f4e99e979a4e.png)
